swagger: '2.0'

info:
  version: "0.0.1"
  title: Course Subjects API

# Describe your paths here
paths:
  # This is a path endpoint. Change it.
  /course-subjects:
    # This is a HTTP operation
    get:
      tags:
       - organizations
       - departments
      # Describe this verb here. Note: you can use markdown
      description: "Gets all `course-subject` objects."
      operationId: getCourseSubjects
      # This is array of GET operation parameters:
      produces:
        - application/json
      # Expected responses for this operation:
      responses:
        # Response code
        "200":
          description: "Successful response"
          schema:
            $ref: "#/definitions/ResultObjects"
        "404":
          description: "Not Found"
          schema:
            $ref: "#/definitions/Error"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/Error"

definitions:
  ResultObjects:
    properties:
      links:
        $ref: "#/definitions/Links"
      data:
        type: array
        items:
          $ref: "#/definitions/ResourceObject"
        
  ResourceObject:
    properties:
      id:
        type: string
      type:
        type: string
      attributes:
        $ref: "#/definitions/Attributes"
        
  Attributes:
    properties:
      abbreviation:
        type: string
        description: "This code is used to filter the list of courses. Example values: 'CS', 'BIO', 'PH'"
      title:
        type: string
        description: "Human readable course title. Example values: 'Computer Science', 'Biology-UO', 'Physics'"
      
  Links:
    properties:
      self:
        type: string
      first:
        type: string
      last:
        type: string
      prev:
        type: string
      next:
        type: string
        
  Error:
    type: object
    properties:
      status:
        type: integer
        format: int32
      developerMessage:
        type: string
      userMesage:
        type: string
      code:
        type: integer
      details:
        type: string
