swagger: '2.0'

info:
  version: "0.0.1"
  title: Grade Schemes API

# Describe your paths here
paths:
  # This is a path endpoint. Change it.
  /grade-schemes:
    # This is a HTTP operation
    get:
      tags:
       - grade-schemes
      # Describe this verb here. Note: you can use markdown
      description: "Gets all `grade-schemes` objects."
      operationId: getGradeSchemes
      # This is array of GET operation parameters:
      produces:
        - application/json
      # Expected responses for this operation:
      responses:
        # Response code
        "200":
          description: "Successful response"
          schema:
            $ref: "#/definitions/ResultObjects"
        "404":
          description: "Not Found"
          schema:
            $ref: "#/definitions/Error"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/Errors"
      security:
        - locations_api_key: []

    

securityDefinitions:

  locations_api_key:
    type: apiKey
    name: locations_api_key
    in: query

definitions:
  ResultObjects:
    properties:
      data:
        type: array
        items:
          $ref: "#/definitions/ResourceObject"
        
  ResourceObject:
    properties:
      id:
        type: string
      type:
        type: string
      attributes:
        $ref: "#/definitions/Attributes"
        
  Attributes:
    properties:
      abbreviation:
        type: string
        description: "Single letter used to describe grading scheme for a course"
      title:
        type: string
        description: "Human readable description for grade scheme"

  Error:
    type: object
    properties:
      status:
        type: integer
        format: int32
      developerMessage:
        type: string
      userMesage:
        type: string
      code:
        type: integer
      details:
        type: string

  Errors:
    title: ArrayOfErrors
    type: array
    items:
      $ref: "#/definitions/Error"
