swagger: '2.0'

info:
  version: "0.0.1"
  title: Open Terms API

# Describe your paths here
paths:
  # This is a path endpoint. Change it.
  /open-terms:
    # This is a HTTP operation
    get:
      tags:
       - open-terms
      # Describe this verb here. Note: you can use markdown
      description: "Gets all `open-terms` objects."
      operationId: getOpenTerms
      # This is array of GET operation parameters:
      produces:
        - application/json
      # Expected responses for this operation:
      responses:
        # Response code
        "200":
          description: "Successful response"
          schema:
            $ref: "#/definitions/ResultObjects"
        "404":
          description: "Not Found"
          schema:
            $ref: "#/definitions/Error"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/Errors"
      security:
        - locations_api_key: []

    

securityDefinitions:

  locations_api_key:
    type: apiKey
    name: locations_api_key
    in: query

definitions:
  ResultObject:
    properties:
      links:
        $ref: "#/definitions/Links"
      data:
        $ref: "#/definitions/ResourceObject"

  ResultObjects:
    properties:
      links:
        $ref: "#/definitions/Links"
      data:
        type: array
        items:
          $ref: "#/definitions/ResourceObject"
        
  ResourceObject:
    properties:
      id:
        type: string
      type:
        type: string
      attributes:
        $ref: "#/definitions/Attributes"
        
  Attributes:
    properties:
      code:
        type: string
      title:
        type: string
      
  Links:
    properties:
      self:
        type: string
      first:
        type: string
      last:
        type: string
      prev:
        type: string
      next:
        type: string

  Error:
    type: object
    properties:
      status:
        type: integer
        format: int32
      developerMessage:
        type: string
      userMesage:
        type: string
      code:
        type: integer
      details:
        type: string

  Errors:
    title: ArrayOfErrors
    type: array
    items:
      $ref: "#/definitions/Error"
